### PR TITLE
deleted search button, edited nonprofit font, added s

### PR DESCRIPTION
**Pull request by RachellCalhoun**
I changed the font of nonprofit on index page, and deleted the search from header.

### CODE REVIEW

**Comment by jinpark** [comment]
@RachellCalhoun you can link to the issue by pasting the url of the issue in your comment 

like #23 

it makes it easier to follow :)

**Comment by RachellCalhoun** [comment]
ok! will do next time

**Comment by RachellCalhoun** [comment]
yes boss! i'm on it!

**Comment by hassanabidpk** [comment]
Looks fine now !

**Pull request merged**
