### PR TITLE
add travis.yml file

### PR DESCRIPTION
**Pull request by jinpark**
also testing travis to see if it works

### CODE REVIEW

**Comment by jinpark** [comment]
image

**Comment by jinpark** [comment]
image

**Comment by jinpark** [comment]
Since we have no tests, they all pass. What a surprise :D

**Comment by jinpark** [comment]
I'm not 100% sure that this will deploy when pushed to master but we'll see

**Comment by hassanabidpk** [comment]
I have one test written for hacks app  : https://github.com/CodeforeveryoneSeoul/codeforeveryone/blob/master/hacks/tests.py

**Pull request merged**
