### PR TITLE
remove viewsoure button

### PR DESCRIPTION
**Pull request by hassanabidpk**
We can add it to footer.

### CODE REVIEW

**Comment by jinpark** [comment]
Are you going to add it in the footer in this PR? or do you want to do it later

**Comment by RachellCalhoun** [comment]
is this newbie friendly? Can you let me do it if you haven't already started?

**Comment by hassanabidpk** [comment]
Where did Rachell's comment go ? :cry:

**Comment by jinpark** [comment]
Ok this is LGTM. @RachellCalhoun will make a PR for adding it to the footer

**Pull request merged**
