### PR TITLE
fix issue #6 Now slug in hack and category model are auto-created

### PR DESCRIPTION
**Pull request by hassanabidpk**

### CODE REVIEW

**Comment by jinpark** [comment]
Hmm, rather than do it this way, I think it makes more sense to have it as a post-save method and make the slugified field be a read only on the admin?

**Comment by jinpark** [comment]
Also tests!

If you write a pull request, always write a corresponding test please

**Comment by hassanabidpk** [comment]
okay

**Comment by hassanabidpk** [comment]
Updated

**Comment by jinpark** [comment]
@hassanabidpk looks like you're still adding to `debug.log` can you remove it from the PR :)

**Comment by hassanabidpk** [comment]
I think , I messed up this pull request.. Debug.logs should be included but empty right ?

**Comment by hassanabidpk** [comment]
One more question : We usually do git commit --amend a lot. But it didnt work out for on github and alway ask about git pull first ( then merge).

**Comment by hassanabidpk** [comment]
This is the error :  FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/CodeforeveryoneSeoul/codeforeveryone/logs/debug.log'

**Comment by jinpark** [comment]
You can just make a blank debug.log file. the `.gitignore` should not track it

**Pull request closed without merging**
